### ISSUE TITLE
1.2.4 Report an Error

### ISSUE THREAD

**Issue by Marxxu3ru** [JohNan/homeassistant-wellbeing#130]
Hi, thanks for your hard work. In this version, a new ‘Smart Mode’ option for the fan has been added, but it still doesn’t work. Also, the Electrolux app has a toggle feature called ‘Silent Fan,’ which limits the fan speed to 2. Is this feature equivalent to ‘Quiet Mode’? I’m also attaching the error log file.
Model Number:EP53-48SWA
[home-assistant_2024-08-23T03-51-05.974Z.log](https://github.com/user-attachments/files/16723699/home-assistant_2024-08-23T03-51-05.974Z.log)
[home-assistant_2024-08-23T03-49-56.075Z.log](https://github.com/user-attachments/files/16723700/home-assistant_2024-08-23T03-49-56.075Z.log)

**Comment by JohNan** [comment]
Thank you. Try https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v1.2.5 and let me know if it works for you.

**Comment by Marxxu3ru** [comment]
Good morning, Johan Nenzén. Thank you for your hard work. The issue with Smart Mode in version 1.2.5 still persists. Could this be related to the fact that the device is in the Asia region? I currently live in Taiwan. I’ve attached the error report for your reference. Thank you.

記錄器: homeassistant.components.websocket_api.http.connection
來源: components/websocket_api/commands.py:241
整合: Home Assistant WebSocket API (相關文件, 問題)
首次發生: 上午10:53:57 (3 事件)
最後紀錄: 上午10:55:39

[281472822881024] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 430, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
  File "/config/custom_components/wellbeing/fan.py", line 140, in async_turn_on
    await self.api.set_work_mode(self.pnc_id, self._preset_mode)
  File "/config/custom_components/wellbeing/api.py", line 391, in set_work_mode
    result = await appliance.send_command(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 93, in send_command
    raise e
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 90, in send_command
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://api.developer.electrolux.one/api/v1/appliances/956006959323006505087076/command'

[home-assistant_2024-08-24T02-57-35.285Z.log](https://github.com/user-attachments/files/16734990/home-assistant_2024-08-24T02-57-35.285Z.log)

**Comment by JohNan** [comment]
I'm not sure. The server respond with error 500 Internal Server Error, which is an error at their side.

Can you enable debug logs and try again and post the logs. I want to see what commands are sent.

**Comment by Marxxu3ru** [comment]
I’m providing you with two files to see if they contain the information you need. Thank you.

[home-assistant_2024-08-24T09-35-36.819Z.log](https://github.com/user-attachments/files/16736085/home-assistant_2024-08-24T09-35-36.819Z.log)
[home-assistant_2024-08-24T09-36-46.052Z.log](https://github.com/user-attachments/files/16736086/home-assistant_2024-08-24T09-36-46.052Z.log)

**Comment by Marxxu3ru** [comment]
Updated to version 1.2.6 and provided the complete logs. I hope this helps you.
The Smart Mode is still not working in version 1.2.6, and there are other error issues as well.

[home-assistant_2024-08-25T09-22-00.213Z.log](https://github.com/user-attachments/files/16739619/home-assistant_2024-08-25T09-22-00.213Z.log)

Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 5:13:03 PM (4 occurrences)
Last logged: 5:14:37 PM
Entity sensor.wellbeing_空氣清淨機_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
Entity sensor.wellbeing_空氣清淨機_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues

This error originated from a custom integration.
Logger: pyelectroluxgroup.appliance
Source: custom_components/wellbeing/api.py:406
integration: Electrolux Wellbeing (documentation, issues)
First occurred: 5:14:15 PM (3 occurrences)
Last logged: 5:14:51 PM
Error sending command '{'UILight': True}' to appliance 956006959323006505087076
Error sending command '{'UILight': False}' to appliance 956006959323006505087076

This error originated from a custom integration.
Logger: pyelectroluxgroup.appliance
Source: custom_components/wellbeing/api.py:394
integration: Electrolux Wellbeing (documentation, issues)
First occurred: 5:16:27 PM (2 occurrences)
Last logged: 5:16:30 PM
Error sending command '{'Workmode': 'Smart'}' to appliance 956006959323006505087076

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:14:15 PM (5 occurrences)
Last logged: 5:16:30 PM
[281472346020384] Unexpected exception
[281472307949152] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/wellbeing/switch.py", line 42, in async_turn_on
    await self.coordinator.api.set_feature_state(self.pnc_id, self._function, True)
  File "/config/custom_components/wellbeing/api.py", line 406, in set_feature_state
    await appliance.send_command(data)
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 93, in send_command
    raise e
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 90, in send_command
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 406, message='Not Acceptable', url='https://api.developer.electrolux.one/api/v1/appliances/956006959323006505087076/command'

**Comment by magdogg** [comment]
I still get the "PUREi9" is not a valid model error. Uninstalling and re adding integration did not work.

**Comment by orangesunny** [comment]
I get this error in logs with the latest 1.2.7, but everything appears to be working fine for now. Here is what I can find in the logs:

```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 00:05:48 (4 occurrences)
Last logged: 00:05:48

Entity sensor.wellbeing_A9old_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
Entity sensor.wellbeing_A9old_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
Entity sensor.wellbeing_A9bed_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
Entity sensor.wellbeing_A9bed_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues

```

**Comment by JohNan** [comment]
> partially related, so I will not start a new issue for now.
> 
> @JohNan, I get this error in logs with the latest 1.2.7, but everything appears to be working fine for now. Here is what I can find in the logs:
> 
> ```
> Logger: homeassistant.components.fan
> Source: components/fan/__init__.py:295
> integration: Fan (documentation, issues)
> First occurred: 00:05:48 (4 occurrences)
> Last logged: 00:05:48
> 
> Entity sensor.wellbeing_A9old_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
> Entity sensor.wellbeing_A9old_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
> Entity sensor.wellbeing_A9bed_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
> Entity sensor.wellbeing_A9bed_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
> 
> ```

Thank you. I'm aware of the logs, but it's nothing that should impact the functionality of the integration.

**Comment by magdogg** [comment]
Got this now: 500, message='Internal Server Error', url='https://api.developer.electrolux.one/api/v1/appliances/950011384049003645087076/info'

API down or something else?

**Comment by JohNan** [comment]
> Got this now: 500, message='Internal Server Error', url='https://api.developer.electrolux.one/api/v1/appliances/950011384049003645087076/info'
> 
> API down or something else?

Looks like that. I get the same error when using their api on the developer portal.

**Comment by JohNan** [comment]
Looks like the reason for the downtime is Electrolux have updated the API after my feedback about missing toggles.

![Screenshot_20240903_213501_Home Assistant](https://github.com/user-attachments/assets/8550d0e5-b994-4bb9-841e-7866974e40dd)

😁

**Comment by Marxxu3ru** [comment]
> 看來停機的原因是，在我反饋缺少切換後，伊萊克斯更新了API。
> 
> ![螢幕截圖_20240903_213501_家庭助理](https://private-user-images.githubusercontent.com/492325/364118430-8550d0e5-b994-4bb9-841e-7866974e40dd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjIzMjksIm5iZiI6MTcyNTQyMjAyOSwicGF0aCI6Ii80OTIzMjUvMzY0MTE4NDMwLTg1NTBkMGU1LWI5OTQtNGJiOS04NDFlLTc4NjY5NzRlNDBkZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMzUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjcyYTc2MDIwNzIyMzRhNjNhOTg1MmM1N2Y0ZTY0NjVhMmQxYWU0MmI1YThhNjZkZjc3NTg3MzU3MGNhMGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UXzBIo9xQB7clEwIv2gTdKxvJWqV7ZWkBSt2gwsx1zI)
> 
> 😁

Hi Johan Nenzén,

After updating to version 1.2.7, I haven’t had much time to test it, but the issue seems to be the same as in version 1.2.6. It looks like you’ve identified the problem, so I’ll wait for the new version to be released and then test it again. Thank you for your hard work.

**Comment by jswetzen** [comment]
> Looks like the reason for the downtime is Electrolux have updated the API after my feedback about missing toggles.
Is that what you call a "breaking fix"? 😁
Huge thanks Johan for you dedication and work!
