### ISSUE TITLE
Failed to perform the action fan/turn_off

### ISSUE THREAD

**Issue by MuppetOwl** [JohNan/homeassistant-wellbeing#132]
Fan turn off function no longer works for my Pure A9 devices.

Failed to perform the action fan/turn_off. Entity fan.wellbeing_fanspeed does not support this service. I'm able to adjust fan speed and see all sensors data without issues. Only turn off/on fan that does not work correct. Have tried to reinstall the plugin and setup again without success. 

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:48:07 (19 occurrences)
Last logged: 17:38:30

[140237753885184] Unexpected exception
[140238015591136] Unexpected exception
[140238206885680] Unexpected exception
[140237955329488] Unexpected exception
[140237753884176] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 981, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity fan.wellbeing_bedroom_fanspeed does not support this service.`

**Comment by JohNan** [comment]
Thank you. Try https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v1.2.5 and let me know if it works for you.

**Comment by MuppetOwl** [comment]
It works now. Thank you for fast fix!
