### ISSUE TITLE
FanEntityFeature not set

### ISSUE THREAD

**Issue by coserotondo** [JohNan/homeassistant-wellbeing#142]
Entity sensor.wellbeing_Purificatore d'aria_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues

Entity sensor.wellbeing_Purificatore d'aria_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
`

**Comment by hyrava** [comment]
I got same error:

Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: August 29, 2024 at 16:48:13 (254 occurrences)
Last logged: 07:25:05

Entity sensor.wellbeing_Ilmanpuhdistin_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues
Entity sensor.wellbeing_Ilmanpuhdistin_Fanspeed (<class 'custom_components.wellbeing.fan.WellbeingFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/JohNan/homeassistant-wellbeing/issues

My device is:
WELLA7
by ELECTROLUX
Firmware: 1.29.5 

And I think this error message in HA log is somehow related:
This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: helpers/debounce.py:137
integration: Electrolux Wellbeing (documentation, issues)
First occurred: 13:18:19 (1 occurrences)
Last logged: 13:18:19

Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.wellbeing.WellbeingDataUpdateCoordinator object at 0x7f8006b0a150>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 657, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Smart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 660, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Smart'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.wellbeing_ilmanpuhdistin_state has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Smart' (<class 'str'>)
