### ISSUE TITLE
1.2.8 Report an Error

### ISSUE THREAD

**Issue by Marxxu3ru** [JohNan/homeassistant-wellbeing#148]
Hi Johan,

The same issue occurs when switching from fan speed mode to smart mode, causing an error to appear. I've attached the complete log file. I wonder if there's any way to resolve this. Thank
[home-assistant_2024-10-04T15-02-36.956Z.log](https://github.com/user-attachments/files/17260615/home-assistant_2024-10-04T15-02-36.956Z.log)

**Comment by Crazyhead90** [comment]
Same, trying to use the "fan speed" switch from "active" to "off" results in the same error:

`Actie fan/turn_off kon niet worden uitgevoerd. 500, message='Internal Server Error', url='https://api.developer.electrolux.one/api/v1/appliances/950011391109001095087076/command'`

**Comment by Crazyhead90** [comment]
Seems to be a server error I think. Playing around with the:
[https://developer.electrolux.one/documentation/reference#getApplianceInfo](https://developer.electrolux.one/documentation/reference#getApplianceInfo)

I can fetch all of the data normally, but when i try to execute the command:
```
{
  "Workmode": "PowerOff"
}
```

It gives a Error 500, same with Workmode Manual. However, doing the same with Workmode Auto, it returns "Devices already in this state". I guess we have to wait for Electrolux to fix it themselves?

**Comment by Marxxu3ru** [comment]
My current issue remains the same:

Errors occur when using a custom integration.

Logger: pyelectroluxgroup.appliance
Source: custom_components/wellbeing/api.py:511
Integration: Electrolux Wellbeing ([related documentation](https://www.home-assistant.io/integrations/wellbeing), [issues](https://github.com/))
First occurred: 7:29:56 PM (2 events)
Last logged: 10:28:39 PM

Error sending command '{'Workmode': 'Smart'}' to appliance 956006959323006505087076

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API ([related documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/))
First occurred: 7:29:56 PM (2 events)
Last logged: 10:28:39 PM

[281471837251632] Unexpected exception  
[281471826080336] Unexpected exception  
Traceback (most recent call last):  
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service  
    response = await hass.services.async_call(  
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call  
    response_data = await coro  
                    ^^^^^^^^^^  
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service  
    return await target(service_call)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call  
    single_response = await _handle_entity_call(  
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call  
    result = await task  
             ^^^^^^^^^^  
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 383, in async_handle_set_preset_mode_service  
    await self.async_set_preset_mode(preset_mode)  
  File "/config/custom_components/wellbeing/fan.py", line 116, in async_set_preset_mode  
    await self.api.set_work_mode(self.pnc_id, self._preset_mode)  
  File "/config/custom_components/wellbeing/api.py", line 511, in set_work_mode  
    result = await appliance.send_command(data)  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 93, in send_command  
    raise e  
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxgroup/appliance.py", line 90, in send_command  
    resp.raise_for_status()  
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status  
    raise ClientResponseError(  
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://api.developer.electrolux.one/api/v1/appliances/956006959323006505087076/command'

Errors occur when using a custom integration.

Logger: pyelectroluxgroup.auth
Source: custom_components/wellbeing/api.py:429
Integration: Electrolux Wellbeing ([related documentation](https://www.home-assistant.io/integrations/wellbeing), [issues](https://github.com/))
First occurred: 5:49:07 PM (7 events)
Last logged: 5:53:38 PM

Failed to get access token: Failed to get access token: 401, message='Unauthorized', url='https://api.developer.electrolux.one/api/v1/token/refresh'
