### ISSUE TITLE
Electrolux Well A7 still not working

### ISSUE THREAD

**Issue by hyrava** [JohNan/homeassistant-wellbeing#52]
I can't reopen older ticket because it is not mine so I created new. 

My Electrolux worked great with this integration for months mut something happened (integration update? HA update?) and it stopped working. 

-----
I have same issue with Well A7. Sometimes integration gets some values from Well A7 but very randomly.

![image](https://github.com/JohNan/homeassistant-wellbeing/assets/73065751/4ecc6f84-e382-4c25-8a94-268223c7f821)

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: helpers/update_coordinator.py:229
Integration: Electrolux Wellbeing (documentation, issues)
First occurred: 12:18:43 (1 occurrences)
Last logged: 12:18:43

Error fetching wellbeing data:

_Originally posted by @hyrava in https://github.com/JohNan/homeassistant-wellbeing/issues/30#issuecomment-1594402634_

**Comment by MickLesk** [comment]
Is the problem still present?

**Comment by hyrava** [comment]
Some hours ago I updated to newest version 1.0.8 and the problem is still present. After update I removed my Well A7 and added it back and that didn't help either.  Now I found some new error messages from log:

2023-08-12 21:17:58.069 DEBUG (MainThread) [custom_components.wellbeing] Finished fetching wellbeing data in 0.235 seconds (success: False)
2023-08-12 21:17:58.069 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/wellbeing/__init__.py", line 94, in _async_update_data
appliances = await self.api.async_get_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/wellbeing/api.py", line 417, in async_get_data
app.setup(data)
File "/config/custom_components/wellbeing/api.py", line 244, in setup
for entity in Appliance._create_entities(data) if entity.attr in data
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/wellbeing/api.py", line 126, in _create_entities
name=f"{FILTER_TYPE[data.get('FilterType_1', 0)]} Life",
~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 50
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/wellbeing/__init__.py", line 99, in _async_update_data
raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/wellbeing/__init__.py", line 123, in async_reload_entry
await async_setup_entry(hass, entry)
File "/config/custom_components/wellbeing/__init__.py", line 53, in async_setup_entry
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in async_config_entry_first_refresh
raise ex
homeassistant.exceptions.ConfigEntryNotReady
