### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Marxxu3ru** [JohNan/homeassistant-wellbeing#75]
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:360
Integration: 開關 ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 上午12:39:07 (3 occurrences)
Last logged: 上午12:46:42

Error while setting up wellbeing platform for switch
Traceback (most recent call last):
  File "/config/custom_components/wellbeing/switch.py", line 15, in async_setup_entry
    WellbeingSwitch(coordinator, entry, pnc_id, "Ionizer"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wellbeing/switch.py", line 26, in __init__
    self._is_on = self.get_entity.state
                  ^^^^^^^^^^^^^^^
  File "/config/custom_components/wellbeing/entity.py", line 28, in get_entity
    return self.get_appliance.get_entity(self.entity_type, self.entity_attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wellbeing/api.py", line 227, in get_entity
    return next(
           ^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
RuntimeError: coroutine raised StopIteration

Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:507
Integration: 風扇 ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 上午12:39:07 (2 occurrences)
Last logged: 上午12:46:42

Error adding entities for domain fan with platform wellbeing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 427, in state_attributes
    data[ATTR_PERCENTAGE_STEP] = self.percentage_step
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 384, in percentage_step
    return 100 / self.speed_count
           ~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:368
Integration: 風扇 ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 上午12:39:07 (2 occurrences)
Last logged: 上午12:46:42

Error while setting up wellbeing platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 427, in state_attributes
    data[ATTR_PERCENTAGE_STEP] = self.percentage_step
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 384, in percentage_step
    return 100 / self.speed_count
           ~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

**Comment by JohNan** [comment]
Try version 1.2.3. It should support your purifier.
